### ISSUE TITLE
Is this code incomplete?

### ISSUE THREAD

**Issue by CheeseBoo** [Guillem96/madgan-pytorch#1]
There seems to be a lack of testing here.

**Comment by Guillem96** [comment]
Yeah WIP.. Sorry for that…

**Comment by CheeseBoo** [comment]
> Yeah WIP.. Sorry for that…

I really like this project! I'm trying to use GAN to build a model. If you have time to complete this project (including training, testing, and evaluating), it will be of great help to me. Thank you very much!
